---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: argocd
spec:
  encryptedData:
    client_id: AgC42sIiutolmNZjDlDFmfymjAYdR4Q6NXvgR+B/otRSn3vO4xKS39eWSDklbSTFrnWNZX8IiZLrAMxpATLSB1fGwQrVnptsUTJ7P0IK82bFlQ5LZBmzLdGfE9oEQ2o1KKAYtDwJpMZmODalvONqSTPgbWJ5ZBt9EDMv5C2SnS1WfOY77c2cPtcPwhwE42y7zH28oOrjPpNSdsBmM4SKWMC6pdiHOy4ymqHG/2PeyavZAMQBrKKkaMM6M1PxXeJdt2ptTmF2ywqbt7HKFx8lMZ8aUS3cBDKZOpHYpBIIQ+xvP1D0aF+p5zOu2kxKvo6+55m3IVcObIex+an37e8O27Xw3noK5diuC+MjlrNhz/KWlIWFrnsH9LdoCeWdZVbabk4TV64fWOUVjdXSngSdV5U4SAUyzROC4255EpjAFtF2wTcSxcstqwetsHxbuwlZGLNQluOPhdKj0Nu5akH0vBIOGxyWm2KiNLDuN6Nwfm3A8YfAuPwC4GBgV9p4OGzuGmGqAG/vBtNwPnhug2hQpulypSEbsBVtGSxO7JRh3H62w5PAcXkKHijtdyDif0r8qKDxMUSPd0xR0lACpQ6a/E9rp+qy0Sz0ckF18pJGhQaaBPCl8O5rLa04lyVIpytrgMFf/IuHxUTMV1VeRHaxtBcvU7JQor7DDdYzrsT25/zZ9phlmwWx+TLvEHyAQnoV39/YgEvehjBqBEiTateYtumxNjwDv/hryBzzKABtWYnyEsfxxLLvn9LoXcboDXZK4WnORQSAnSILydsXb109U74=
    client_secret: AgBJyGoX1XkmROBVBwE+umMPs/vGz8qnruYPZPYCDnN83kzsRVBbANI4K547YHY9mjoAAy0wsKDYw3FzuWT5vDgdnFN2Va0TUq4KHpHaH2dnpxKlBmWnddoSX02FCMVl0UGQ+eVnz5oYep1+9BmvLdIx3otDFzV2bwQoRuy453QIg1REz/hviAhKo9KdT0fXxNeNODI5P9YzL39H1DawZ+LfCF/alI4bZCauGDOoQK2jPpl7affIbb/+aETeSYhs9fbnVt1/2sJ45IcMCwgauWDVDLWguqRWb1Nle5tx9XcOY1QiNhq6NQKDVjTyAV4LQHUAuVQ0+L8Z6KLV3VHlr2RkGb2k5nt/FbbXZvxDhCdusszV8VHbCaGWx/nzttByHdtFN0kD4xRBXmpHGQU1ytNrPZN8l3XLV6YEWyJ8KjaHn4DtU9b3gC5/Bp1PfJM5oHGUIIaVsdTxzQ7p9RQXhuBGXuPGhkzrj1e1SrTnCjelXkXeFvNVa6P8mhALb4Bq/P3MJqWesOW/wethVza/zRoXgtIGo12ddqIng4yTGvTobB+eKJz0txbRU+NBsBZG9hGx56KSF+f9mxdy+/+oVsNgiEqdhYQGEIc2R+rr88EuuRjPXFhi91bFkQMnMvSBNMtXPaQtsEDXVQMild5ht4qo01Kd8p5JSynT1fmIHOgLIgVrR9dGnifqk00nyN5vkrLh1Vz1iyFfLlzyQwMr6hhs1w==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: argocd
