---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: household-task-manager
spec:
  encryptedData:
    DATABASE_URL: AgAGwkotiqvlLrw4QWSELz9J9JmRLDlEH8wmv4mfL/g1gJY/m1Y7UtaANLwySNAvSpeGMEipEQBn1WHIvjMhANCThv2pyn/e7LFWE8vMzPaAfAhG4svvqpjcYfSoqciJsRm098AG7xWnej7qtVXmjy2gParpyVFxKhRQmG2ElbkmE8G24q7/eQjCRsLW6+j8YP76i4nVqntswKVAlKKTCPiAU8Rfiu+KEfg+UH5Cku2AMq62wCXgsoCfonK1Gu1VCF3RplXmPMcy0oql/+5Z04Bnw2JcPs/vnPFvuhcelAS6dCi8+D6ZJeNTMO6/oo3M0PB64rp2OOm98d2rmC/THQNekxeEVQSrZkzfd6RMbsKW1HnSftT2PV8Zh21Q7NhmR/XjuH74o7SDBkoS7i2nmTelMZ9WC+gIVPHzrIAGWZw3KYEbWW0jR8taBFtl97eWOnMBAP1ZQTD5wBtCarMyLrw9QebpWVFGDSqIt1c0L7StZji+Ihl6mYtwZoH5gWnVfJmery3sxIGp3/RwpjV4G1Fo8weQNegkGJflM2aXBzMzQJdBTraWGTd+dPYPtXJDWm/JgcPfgNSj992bHwaE7d/DpDzCh51EgGTw7MJZ5CTW1YA4XMKO0+JpcIxc1apmQemBKZ2VGuJsTgOVA/Xqe3E+WEoFozD/Zk5HQfuWBtTJ6q4ScQu9UKE6VpbUaNuUqqF56OB+dYfvL9wMSnZRUnsttrQWGOegbbeMvM1PwjVOidzzGRQt09UJKLQvzJkY5fcazzE7qlZLVr4lo7hzZmRzeeoy0Artouh+h8qaAAw=
    SECRET_KEY: AgAk3vL5Cirp2lHwAT9y+D1PGtiIfGPOPB64o9LYtJhqNjqYRxvYwP1aYF1GhktoIn3rdona0F1NAX5TTl5Vc/Hvw1OWrOWvHPKYdTv4Hrr5G++88DSZAIeMOUXsUPzTvEDTB7JB6qivi+/mGL7xYSHKpOXKgShC5gWq/CXf6GOBqSP5HYC4asFlbmTuRYtz/hLiVEb2hfH7eBZo5RmHmJeddNK2NR6hqzz51WqQCrpDQP4Ud/TXZQ0BZ3j0zasBPESQYiZcEx1MifFvcPJ3qX0sQc1RPjO26yXVcyNH7j9q5MqjyLTTnKF8PCPNpkkfqjixItmmiSguU4Jzpwc3HuEKNVIdULuUkjAzWj3TBDDXPmQMtUdj5VbWgVfqa8fiN0p0NzeiYZf0FJQ1XwOhxqxjf8ySK3GiP3i5R2p2ppzf6nIUDz41+OzNqWHdizRifnLzsOoyjLfpHkoB74hJKZP3CXu7wnVW1+9RCNURLnXNm7DdMqnO6hi+EhVFWbenN568IGSl0oxcvCHstohQntumBeJVGdBEho0PBauhjP4GfosNslEB062HgYuAZ1j4FZ+/MgfEyFEDimqT1ozxSjFm+xmoomklCRlXMXbJPxOsCoVpCYHU8Lk859PtxJrEYzp/wBllMC2dAVfPFJiDRv9/A62jl9UFfN9YEHRH3voET1JGJEIhTKRqbxrbvBhaOjZZvlBdr26zCNj8ApMyfYpZopt88sYK3JbtYMF0d0iukOe14VKXn/rz6nEyWWRK4hXujguE6g/GPcvi/bvhMq3/
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: household-task-manager
