apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-nfs
  namespace: household-task-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 10Gi
