---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secret
  namespace: household-task-manager
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBIB2pbZjA7HwdcBsVVkFZQs4yKKgPy7urtUEJuz0+RSVjaSjT6ZNXunuXhPcy6C6pW9LfitUvuU9oPUhPbiQC7+eFRUinrY14gRfIpSXHPj0SdG0meisUyTGOtJLFEG4vabFvQXTtdawaCLB6v2vUwdHX/m1lCOrO1wm2QnTtHUWzP7nFo25xhD5SQSGw7oT62l1TpaQFnWTZ4iO1p7KJyyzCnR93Aoxe2G1mdFpw42qnnp9GXtfax9S1YyNZYbb0NNMcWV2XgYZrJ3ZfaOuETsYCEiceAp3hhPIn40KfYDp3wqJCED75uWaAlj5QahM9pplgetMdYWkP93e/CTL3ATJbBiUJf1wW0D+0SfaiI6Yq0IIHUn69efrELkUZccelunelohZAVcQe3nPnj7qPBpxxcBN4QV9tHgcb4Gy30OKFHKPxtvJgor6DuZcg/pTX8tciqhl9lwK4xz2MKYHPZoyzZaTTofz+Ss6cyWeUZKxUEyQDhSCzOUTHfiD6fX8255iiw7dR1hCUKGz1Q9Y4+pG+SHyIMGEZrdNe/PP1Ne0zgVPaud/UmrBvQFR91Coq3er4z3dtlseDzBBQStBauc4eWCpkhcn20FSaJE6xD+TWmi0JyP/IoqxJNtxwE3lt6WIAjQcF+/xd0gOTnU2Sy0nemKVt0m9iCpsVxeaCb6f2DB8vLnwJm60LKZAFyk27BjHLQG+2LWCDtBnC4T9F96uoobVnSneGWJ/nEzl5ArA==
  template:
    metadata:
      creationTimestamp: null
      name: database-secret
      namespace: household-task-manager
